apiVersion: batch/v1
kind: Job
metadata:
  name: content-copy-job
spec:
  template:
    spec:
      containers:
        - name: copy-content
          image: busybox
          command: ["sh", "-c", "echo 'Hello from NFS!' > /mnt/nfs/hello.html"]
          volumeMounts:
            - name: nfs-volume
              mountPath: /mnt/nfs
      volumes:
        - name: nfs-volume
          persistentVolumeClaim:
            claimName: nfs-pvc
      restartPolicy: Never
